FROM jenkins/jenkins:lts
USER root

# Install the Docker CLI so Jenkins can talk to your laptop's Docker engine
RUN apt-get update && apt-get install -y docker.io

# Switch back to the jenkins user for security
USER jenkins
